# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: website
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - run: yarn build
    - name: Publish build assets
      uses: vv13/rsync-publisher@v1
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER_DEST: ${{ secrets.SERVER_DEST }}
        FOLDER: "website/out"
        OPTION: "-avzr --delete"
